version: '3.8'
services:
  bot:
    build: .
    container_name: discord-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - NODE_ENV=production
      - WEB_PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped 
    volumes:
      - ./data:/data
